version: '3.5'
services:
  payroll-frontend:
    image: 'payroll-frontend:production'
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - './env:/opt/app/.env'
      - './build:/opt/app/build'
